services:
  postgres:
    image: postgres:16.9-alpine
    container_name: mymood-postgres
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    env_file:
      - ./api/.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
