services:
  postgres:
    image: postgres:16.9-alpine
    container_name: mymood-postgres
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    env_file:
      - ./api/.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: mymood-api
    ports:
      - '${API_PORT:-3000}:3000'
    env_file:
      - ./api/.env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:@postgres:5432/mymood
    restart: unless-stopped

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: mymood-admin
    ports:
      - '${ADMIN_PORT:-80}:80'
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
